name: AlphaMind Local
values:
  - key: baseUrl
    value: 'http://localhost:8000'
    enabled: true
  - key: apiVersion
    value: v1
    enabled: true
  - key: adminEmail
    value: admin@alphamind.ai
    enabled: true
  - key: adminPassword
    value: admin123
    enabled: true
  - key: userEmail
    value: testuser@alphamind.ai
    enabled: true
  - key: userPassword
    value: user123
    enabled: true
  - key: authToken
    value: ''
    enabled: true
  - key: adminToken
    value: ''
    enabled: true
  - key: createdUserId
    value: ''
    enabled: true
  - key: testStockSymbol
    value: RELIANCE
    enabled: true
