""" Add is_paid to invoices

Revision ID: 17529e08370a
Revises: 9d09d74a48b3
Create Date: 2026-06-17 14:14:50.555151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17529e08370a'
down_revision: Union[str, Sequence[str], None] = '9d09d74a48b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('is_paid', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'is_paid')
    # ### end Alembic commands ###
